### ISSUE TITLE
Issue with importing css files

### ISSUE THREAD

**Issue by normanrz** [koluch/esbuild-plugin-sass#3]
My main stylesheet is a `.scss` file from which I am trying to import a bunch of `.css` files from `node_modules`. Unfortunately, that doesn't work, because this plugin seems to move the files to a temp folder without a link to the node modules folder.
Interestingly, imports of `.scss` files from the node modules seems to work.

I prepared a quick example for reproducing the issue: https://github.com/normanrz/esbuild-sass-bug
Run with `yarn install && node build.js`.

Thanks for your work in providing this plugin!

**Comment by koluch** [comment]
Hi @normanrz! Sorry for late response, github haven't sent me notification for some reason. The reason CSS imports handled differently is that SASS [treats CSS imports with `.css` specified](https://sass-lang.com/documentation/at-rules/import#plain-css-imports) as native CSS imports and doesn't translate them. Then, esbuild fails to load them, because `@import` supports specifing relative urls without `url(...)` syntax, and my plugin didn't support it. I fixed this case in v.0.3.4 patch, it should work properly now.

**Comment by normanrz** [comment]
Thank you very much! I now integrated your plugin into my build script. Works great!
